import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-7xl font-bold text-cyan-300 md:text-red-600 lg:text-yellow-600'>
          font
        </h1>
        <div className='border border-blue-500 py-4 px-5'>afasdf</div>
      </main>
    </>
  )
}
